"""MariaDB raw staging adapter for brand-activity source rows."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import Final
from typing import TypeAlias

from pipeline.scripts.etl.brand_activity.ingest_csd import stage_ddl as csd_stage_ddl
from pipeline.scripts.etl.brand_activity.ingest_keyword_meeting import stage_ddl as km_stage_ddl
from pipeline.scripts.etl.brand_activity.km_core import JsonValue, KeywordEvent, MeetingEvent, text_sha256
from pipeline.scripts.etl.brand_activity.raw_extract import CsdSourceRow
from pipeline.scripts.etl.brand_activity.raw_schema import RAW_DDL
from pipeline.scripts.etl.brand_activity.raw_stage_refresh import refresh_stage
from pipeline.scripts.etl.brand_activity.raw_staging import (
    csd_dedup_key,
    keyword_dedup_key,
    meeting_dedup_key,
)


DbValue: TypeAlias = str | int | None
DbTuple: TypeAlias = tuple[DbValue, ...]
BRAND_ACTIVITY_SCHEMA_PATTERN: Final = re.compile(r"^jw_brand_activity_[A-Za-z0-9_]+$")


@dataclass(frozen=True, slots=True)
class DbConfig:
    """Connection and schema names for isolated local staging."""

    host: str
    port: int
    user: str
    password: str
    raw_schema: str
    stage_schema: str


@dataclass(frozen=True, slots=True)
class SourceRows:
    """Parsed source rows ready for raw and derived-stage loading."""

    csd: list[CsdSourceRow]
    keyword: list[KeywordEvent]
    meeting: list[MeetingEvent]


@dataclass(frozen=True, slots=True)
class LoadStats:
    """Row-count evidence for one load pass."""

    raw_before: dict[str, int]
    raw_after: dict[str, int]
    inserted: dict[str, int]
    stage_rows: dict[str, int]


def quote_stage_name(schema: str, expected: str) -> str:
    """Allow the isolated schema or an explicit brand-activity scratch schema."""
    if schema != expected and BRAND_ACTIVITY_SCHEMA_PATTERN.fullmatch(schema) is None:
        raise ValueError(f"refusing schema {schema!r}; expected {expected!r} or brand-activity scratch schema")
    return schema


def load_sources(config: DbConfig, rows: SourceRows, window: tuple[str, str]) -> LoadStats:
    """Insert raw rows idempotently and refresh derived stage tables."""
    import pymysql

    raw_schema = quote_stage_name(config.raw_schema, "jw_brand_activity_raw_stage")
    stage_schema = quote_stage_name(config.stage_schema, "jw_brand_activity_stage")
    connection = pymysql.connect(
        host=config.host,
        port=config.port,
        user=config.user,
        password=config.password,
        charset="utf8mb4",
        autocommit=False,
        connect_timeout=8,
    )
    try:
        with connection.cursor() as cursor:
            _execute_ddl(cursor, RAW_DDL.format(raw_schema=raw_schema))
            _execute_ddl(cursor, csd_stage_ddl(stage_schema))
            _execute_ddl(cursor, km_stage_ddl(stage_schema))
            before = _raw_counts(cursor, raw_schema)
            inserted = {
                "raw_csd_channel_dynamics": _insert_csd(cursor, raw_schema, rows.csd),
                "raw_keyword_events": _insert_keyword(cursor, raw_schema, rows.keyword),
                "raw_meeting_events": _insert_meeting(cursor, raw_schema, rows.meeting),
            }
            after = _raw_counts(cursor, raw_schema)
            stage_rows = refresh_stage(cursor, raw_schema, stage_schema, window)
        connection.commit()
        return LoadStats(raw_before=before, raw_after=after, inserted=inserted, stage_rows=stage_rows)
    except pymysql.MySQLError:
        connection.rollback()
        raise
    finally:
        connection.close()


def _execute_ddl(cursor: object, ddl: str) -> None:
    """Execute semicolon-separated DDL generated by local scripts."""
    for statement in ddl.split(";"):
        sql = statement.strip()
        if sql:
            cursor.execute(sql)


def _raw_counts(cursor: object, schema: str) -> dict[str, int]:
    """Count raw rows in all brand-activity raw tables."""
    result: dict[str, int] = {}
    for table in ("raw_csd_channel_dynamics", "raw_keyword_events", "raw_meeting_events"):
        cursor.execute(f"SELECT COUNT(*) FROM `{schema}`.`{table}`")
        result[table] = int(cursor.fetchone()[0])
    return result


def _insert_csd(cursor: object, schema: str, rows: list[CsdSourceRow]) -> int:
    """Insert raw CSD rows, deduping only same workbook row reloads."""
    sql = f"""
        INSERT IGNORE INTO `{schema}`.`raw_csd_channel_dynamics`
        (source_dataset, source_file, source_file_sha256, source_sheet, source_row_no, source_period_ym,
         period_ym, market, jw_channel, region, master_product, manufacturer, representing_company, metric,
         product_details, selected_for_stage, dedup_key, source_row_key, row_hash, raw_payload_json)
        VALUES ({", ".join(["%s"] * 20)})
    """
    cursor.executemany(sql, [_csd_tuple(row) for row in rows])
    return int(cursor.rowcount)


def _insert_keyword(cursor: object, schema: str, events: list[KeywordEvent]) -> int:
    """Insert raw Keyword events with source-file/row idempotency."""
    sql = f"""
        INSERT IGNORE INTO `{schema}`.`raw_keyword_events`
        (source_dataset, period_ym, visit_location, specialty, representing_company, product_name,
         therapeutic_class, keyword_text, interest, prescription_frequency, prescription_evolution,
         abstract_lit, patient_lit, promotional_lit, samples_left, other_materials_left,
         what_other_materials, other_comments, source_file, source_sheet, source_row_no,
         source_file_sha256, dedup_key, row_hash, raw_payload_json)
        VALUES ({", ".join(["%s"] * 25)})
    """
    cursor.executemany(sql, [_keyword_tuple(event) for event in events])
    return int(cursor.rowcount)


def _insert_meeting(cursor: object, schema: str, events: list[MeetingEvent]) -> int:
    """Insert raw Meeting events with source-file/row idempotency."""
    sql = f"""
        INSERT IGNORE INTO `{schema}`.`raw_meeting_events`
        (source_dataset, meeting_date, period_ym, meeting_topic, meeting_format, pharma_sponsor,
         non_pharma_sponsor, no_at_meeting, product_name, therapeutic_class, prescription_frequency,
         prescription_evolution, interest, verbatim_message, other_comments, source_file, source_sheet,
         source_row_no, source_file_sha256, dedup_key, row_hash, raw_payload_json)
        VALUES ({", ".join(["%s"] * 22)})
    """
    cursor.executemany(sql, [_meeting_tuple(event) for event in events])
    return int(cursor.rowcount)


def _csd_tuple(row: CsdSourceRow) -> DbTuple:
    """Return the raw CSD DB tuple."""
    payload = _payload(row.to_json())
    stage_row = row.to_stage_row()
    return (
        "csd",
        row.source_file,
        row.source_file_sha256,
        row.source_sheet,
        row.source_row_no,
        row.source_period_ym,
        row.period_ym,
        row.market,
        row.jw_channel,
        row.region,
        row.master_product,
        row.manufacturer,
        row.representing_company,
        "product_details",
        row.product_details,
        int(row.selected_for_stage),
        csd_dedup_key(stage_row),
        text_sha256(f"csd\x1f{row.source_file}\x1f{row.source_sheet}\x1f{row.source_row_no}"),
        text_sha256(payload),
        payload,
    )


def _keyword_tuple(event: KeywordEvent) -> DbTuple:
    """Return the raw Keyword DB tuple."""
    payload = _payload(event.to_stage_row())
    return (
        "keyword",
        event.period_ym,
        event.visit_location,
        event.specialty,
        event.representing_company,
        event.product_name,
        event.therapeutic_class,
        event.keyword_text,
        event.interest,
        event.prescription_frequency,
        event.prescription_evolution,
        event.abstract_lit,
        event.patient_lit,
        event.promotional_lit,
        event.samples_left,
        event.other_materials_left,
        event.what_other_materials,
        event.other_comments,
        event.source_file,
        event.source_sheet,
        event.source_row_no,
        event.source_file_sha256,
        keyword_dedup_key(event),
        text_sha256(payload),
        payload,
    )


def _meeting_tuple(event: MeetingEvent) -> DbTuple:
    """Return the raw Meeting DB tuple."""
    payload = _payload(event.to_stage_row())
    return (
        "meeting",
        event.meeting_date,
        event.period_ym,
        event.meeting_topic,
        event.meeting_format,
        event.pharma_sponsor,
        event.non_pharma_sponsor,
        event.no_at_meeting,
        event.product_name,
        event.therapeutic_class,
        event.prescription_frequency,
        event.prescription_evolution,
        event.interest,
        event.verbatim_message,
        event.other_comments,
        event.source_file,
        event.source_sheet,
        event.source_row_no,
        event.source_file_sha256,
        meeting_dedup_key(event),
        text_sha256(payload),
        payload,
    )


def _payload(row: dict[str, JsonValue]) -> str:
    """Serialize a row deterministically for raw storage and hashing."""
    return json.dumps(row, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
