"""MariaDB raw staging adapter for brand-activity source rows."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import Final
from typing import TypeAlias

from pipeline.scripts.etl.brand_activity.ingest_csd import stage_ddl as csd_stage_ddl
from pipeline.scripts.etl.brand_activity.ingest_keyword_stage import stage_ddl as keyword_stage_ddl
from pipeline.scripts.etl.brand_activity.km_core import JsonValue, KeywordEvent, text_sha256
from pipeline.scripts.etl.brand_activity.raw_extract import CsdSourceRow
from pipeline.scripts.etl.brand_activity.raw_schema import RAW_DDL
from pipeline.scripts.etl.brand_activity.raw_stage_refresh import refresh_stage
from pipeline.scripts.etl.brand_activity.raw_staging import (
    StageDataset,
    StageScope,
    csd_dedup_key,
    datasets_for_stage_scope,
    keyword_dedup_key,
    recent_month_window,
)


DbValue: TypeAlias = str | int | None
DbTuple: TypeAlias = tuple[DbValue, ...]
BRAND_ACTIVITY_SCHEMA_PATTERN: Final = re.compile(
    r"^(?:jw_brand_activity_|jw_ingest_)[A-Za-z0-9_]+$"
)


@dataclass(frozen=True, slots=True)
class DbConfig:
    """Connection and schema names for isolated local staging."""

    host: str
    port: int
    user: str
    password: str
    raw_schema: str
    stage_schema: str


@dataclass(frozen=True, slots=True)
class SourceRows:
    """Parsed source rows ready for raw and derived-stage loading."""

    csd: list[CsdSourceRow]
    keyword: list[KeywordEvent]


@dataclass(frozen=True, slots=True)
class LoadStats:
    """Row-count evidence for one load pass."""

    raw_before: dict[str, int]
    raw_after: dict[str, int]
    inserted: dict[str, int]
    stage_before: dict[str, int]
    stage_rows: dict[str, int]


def quote_stage_name(schema: str, expected: str) -> str:
    """Allow the isolated schema or an explicit brand-activity scratch schema."""
    if schema != expected and BRAND_ACTIVITY_SCHEMA_PATTERN.fullmatch(schema) is None:
        raise ValueError(f"refusing schema {schema!r}; expected {expected!r} or brand-activity scratch schema")
    return schema


def load_sources(
    config: DbConfig,
    rows: SourceRows,
    window: tuple[str, str] | None,
    stage_scope: StageScope = "all",
) -> LoadStats:
    """Insert raw rows idempotently and refresh derived stage tables."""
    import pymysql

    raw_schema = quote_stage_name(config.raw_schema, "jw_brand_activity_raw_stage")
    stage_schema = quote_stage_name(config.stage_schema, "jw_brand_activity_stage")
    datasets = datasets_for_stage_scope(stage_scope)
    connection = pymysql.connect(
        host=config.host,
        port=config.port,
        user=config.user,
        password=config.password,
        charset="utf8mb4",
        autocommit=False,
        connect_timeout=8,
    )
    try:
        with connection.cursor() as cursor:
            _execute_ddl(cursor, RAW_DDL.format(raw_schema=raw_schema))
            if "csd" in datasets:
                _execute_ddl(cursor, csd_stage_ddl(stage_schema))
            if "keyword" in datasets:
                _execute_ddl(cursor, keyword_stage_ddl(stage_schema))
            before = _raw_counts(cursor, raw_schema, datasets)
            stage_before = _stage_counts(cursor, stage_schema, datasets)
            inserted: dict[str, int] = {}
            if "csd" in datasets:
                inserted["raw_csd_channel_dynamics"] = _insert_csd(cursor, raw_schema, rows.csd)
            if "keyword" in datasets:
                inserted["raw_keyword_events"] = _insert_keyword(cursor, raw_schema, rows.keyword)
            after = _raw_counts(cursor, raw_schema, datasets)
            effective_window = window
            if effective_window is None:
                max_period = _max_raw_period(cursor, raw_schema, datasets)
                if max_period is None:
                    raise ValueError(f"no raw rows available for stage_scope={stage_scope}")
                effective_window = recent_month_window(max_period)
            stage_rows = refresh_stage(
                cursor,
                raw_schema,
                stage_schema,
                effective_window,
                stage_scope=stage_scope,
            )
        connection.commit()
        return LoadStats(
            raw_before=before,
            raw_after=after,
            inserted=inserted,
            stage_before=stage_before,
            stage_rows=stage_rows,
        )
    except pymysql.MySQLError:
        connection.rollback()
        raise
    finally:
        connection.close()


def _execute_ddl(cursor: object, ddl: str) -> None:
    """Execute semicolon-separated DDL generated by local scripts."""
    for statement in ddl.split(";"):
        sql = statement.strip()
        if sql:
            cursor.execute(sql)


def _raw_counts(cursor: object, schema: str, datasets: tuple[StageDataset, ...] = ("csd", "keyword")) -> dict[str, int]:
    """Count raw rows in the brand-activity raw tables touched by this load."""
    result: dict[str, int] = {}
    for table in _raw_tables_for_datasets(datasets):
        cursor.execute(f"SELECT COUNT(*) FROM `{schema}`.`{table}`")
        result[table] = int(cursor.fetchone()[0])
    return result


def _raw_tables_for_datasets(datasets: tuple[StageDataset, ...]) -> tuple[str, ...]:
    """Map source datasets to raw storage tables."""
    tables: list[str] = []
    if "csd" in datasets:
        tables.append("raw_csd_channel_dynamics")
    if "keyword" in datasets:
        tables.append("raw_keyword_events")
    return tuple(tables)


def _stage_counts(cursor: object, schema: str, datasets: tuple[StageDataset, ...]) -> dict[str, int]:
    tables: list[str] = []
    if "csd" in datasets:
        tables.append("csd_channel_dynamics_stage")
    if "keyword" in datasets:
        tables.append("km_keyword_event_stage")
    result: dict[str, int] = {}
    for table in tables:
        cursor.execute(f"SELECT COUNT(*) FROM `{schema}`.`{table}`")
        result[table] = int(cursor.fetchone()[0])
    return result


def _max_raw_period(
    cursor: object,
    schema: str,
    datasets: tuple[StageDataset, ...],
) -> str | None:
    maxima: list[str] = []
    for table in _raw_tables_for_datasets(datasets):
        cursor.execute(f"SELECT MAX(period_ym) FROM `{schema}`.`{table}`")
        value = cursor.fetchone()[0]
        if value:
            maxima.append(str(value))
    return max(maxima) if maxima else None


def _insert_csd(cursor: object, schema: str, rows: list[CsdSourceRow]) -> int:
    """Insert raw CSD rows, deduping only same workbook row reloads."""
    sql = f"""
        INSERT IGNORE INTO `{schema}`.`raw_csd_channel_dynamics`
        (source_dataset, source_file, source_file_sha256, source_sheet, source_row_no, source_period_ym,
         period_ym, market, jw_channel, region, master_product, manufacturer, representing_company, metric,
         product_details, selected_for_stage, dedup_key, source_row_key, row_hash, raw_payload_json)
        VALUES ({", ".join(["%s"] * 20)})
    """
    cursor.executemany(
        sql,
        [tuple(csd_raw_record(row).values()) for row in rows],
    )
    return int(cursor.rowcount)


def _insert_keyword(cursor: object, schema: str, events: list[KeywordEvent]) -> int:
    """Insert raw Keyword events with source-file/row idempotency."""
    sql = f"""
        INSERT IGNORE INTO `{schema}`.`raw_keyword_events`
        (source_dataset, period_ym, visit_location, specialty, representing_company, product_name,
         therapeutic_class, keyword_text, interest, prescription_frequency, prescription_evolution,
         abstract_lit, patient_lit, promotional_lit, samples_left, other_materials_left,
         what_other_materials, other_comments, source_file, source_sheet, source_row_no,
         source_file_sha256, dedup_key, row_hash, raw_payload_json)
        VALUES ({", ".join(["%s"] * 25)})
    """
    cursor.executemany(sql, [_keyword_tuple(event) for event in events])
    return int(cursor.rowcount)


def csd_raw_record(row: CsdSourceRow) -> dict[str, DbValue]:
    """Return the canonical ordered raw CSD record."""
    payload = _payload(row.to_json())
    stage_row = row.to_stage_row()
    values: DbTuple = (
        "csd",
        row.source_file,
        row.source_file_sha256,
        row.source_sheet,
        row.source_row_no,
        row.source_period_ym,
        row.period_ym,
        row.market,
        row.jw_channel,
        row.region,
        row.master_product,
        row.manufacturer,
        row.representing_company,
        "product_details",
        row.product_details,
        int(row.selected_for_stage),
        csd_dedup_key(stage_row),
        text_sha256(f"csd\x1f{row.source_file}\x1f{row.source_sheet}\x1f{row.source_row_no}"),
        text_sha256(payload),
        payload,
    )
    columns = (
        "source_dataset", "source_file", "source_file_sha256", "source_sheet",
        "source_row_no", "source_period_ym", "period_ym", "market", "jw_channel",
        "region", "master_product", "manufacturer", "representing_company", "metric",
        "product_details", "selected_for_stage", "dedup_key", "source_row_key",
        "row_hash", "raw_payload_json",
    )
    return dict(zip(columns, values, strict=True))


def _keyword_tuple(event: KeywordEvent) -> DbTuple:
    """Return the raw Keyword DB tuple."""
    payload = _payload(event.to_stage_row())
    return (
        "keyword",
        event.period_ym,
        event.visit_location,
        event.specialty,
        event.representing_company,
        event.product_name,
        event.therapeutic_class,
        event.keyword_text,
        event.interest,
        event.prescription_frequency,
        event.prescription_evolution,
        event.abstract_lit,
        event.patient_lit,
        event.promotional_lit,
        event.samples_left,
        event.other_materials_left,
        event.what_other_materials,
        event.other_comments,
        event.source_file,
        event.source_sheet,
        event.source_row_no,
        event.source_file_sha256,
        keyword_dedup_key(event),
        text_sha256(payload),
        payload,
    )


def _payload(row: dict[str, JsonValue]) -> str:
    """Serialize a row deterministically for raw storage and hashing."""
    return json.dumps(row, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
