FROM nginx:1.27-alpine

ARG OCI_SOURCE
ARG OCI_REVISION
ARG OCI_CREATED
ARG JW_SOURCE_TREE_SHA
ARG JW_SOURCE_BRANCH

RUN test -n "$OCI_SOURCE" \
    && printf '%s' "$OCI_REVISION" | grep -Eq '^[0-9a-f]{40}$' \
    && printf '%s' "$OCI_CREATED" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$' \
    && printf '%s' "$JW_SOURCE_TREE_SHA" | grep -Eq '^[0-9a-f]{40}$' \
    && test -n "$JW_SOURCE_BRANCH"

LABEL org.opencontainers.image.source="$OCI_SOURCE" \
      org.opencontainers.image.revision="$OCI_REVISION" \
      org.opencontainers.image.created="$OCI_CREATED" \
      com.jw.source.tree-sha="$JW_SOURCE_TREE_SHA" \
      com.jw.source.branch="$JW_SOURCE_BRANCH"

ENV NGINX_ENVSUBST_OUTPUT_DIR=/usr/share/nginx/html

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY deploy/config.json.template /etc/nginx/templates/config.json.template
COPY deploy/15-runtime-config-validate.sh /docker-entrypoint.d/15-runtime-config-validate.sh
COPY dist/ /usr/share/nginx/html/

EXPOSE 8090
