"""Canonical contracts introduced ahead of the routing cutover."""

from .base import ContractModel
from .answer import (
    AnswerModel,
    AnswerSection,
    ChartIntent,
    ContractFacetFailure,
    SectionKind,
    SupportedClaim,
    TableCell,
    TableRow,
)
from .capability import (
    capability_snapshot_from_source_class,
    parameter_resolution,
)
from .query import (
    BrandCapabilitySnapshot,
    CatalogSourceClass,
    EntityKind,
    EntityRef,
    MarketAxisSpec,
    MarketSource,
    MeasureKind,
    MeasureSpec,
    NativeMarketMeasure,
    ParameterIssueReason,
    ParameterResolution,
    ParameterStatus,
    PeriodGranularity,
    PeriodSpec,
    PortalMarketView,
    ResolutionStatus,
    ResolvedQuery,
    SourceMeasureCapability,
    UnitSpec,
)
from .evidence import (
    EvidenceBundle,
    EvidenceFact,
    EvidenceItem,
    EvidenceStatus,
    PartialFailure,
    RationaleFact,
    RationaleKind,
    SourceStatus,
)
from .validation import (
    RenderAuthorization,
    ValidationDecision,
    ValidationReport,
    ValidationSeverity,
    ValidationViolation,
)
from .routing import (
    CanonicalRouteDecision,
    RejectedRoute,
    RouteDecision,
    RouteFieldComparison,
    RouteMode,
    RouteShadowComparison,
)

__all__ = (
    "AnswerModel",
    "AnswerSection",
    "BrandCapabilitySnapshot",
    "CanonicalRouteDecision",
    "CatalogSourceClass",
    "ContractModel",
    "ContractFacetFailure",
    "ChartIntent",
    "EntityKind",
    "EntityRef",
    "EvidenceBundle",
    "EvidenceFact",
    "EvidenceItem",
    "EvidenceStatus",
    "MarketAxisSpec",
    "MarketSource",
    "MeasureKind",
    "MeasureSpec",
    "NativeMarketMeasure",
    "ParameterIssueReason",
    "ParameterResolution",
    "ParameterStatus",
    "PartialFailure",
    "PeriodGranularity",
    "PeriodSpec",
    "PortalMarketView",
    "ResolutionStatus",
    "RejectedRoute",
    "ResolvedQuery",
    "RouteDecision",
    "RouteFieldComparison",
    "RouteMode",
    "RouteShadowComparison",
    "RationaleFact",
    "RationaleKind",
    "RenderAuthorization",
    "SectionKind",
    "SourceStatus",
    "SourceMeasureCapability",
    "SupportedClaim",
    "TableCell",
    "TableRow",
    "UnitSpec",
    "ValidationDecision",
    "ValidationReport",
    "ValidationSeverity",
    "ValidationViolation",
    "capability_snapshot_from_source_class",
    "parameter_resolution",
)
