apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw-chat-agent-poc
  namespace: llmops
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: CHAT_QUERY_DB_NAME
              value: jw_mart_d2_stage_20260630_r2
            - name: CHAT_CATALOG_DB_NAME
              value: jw_mart_d2_stage_20260630_r2
            - name: CHAT_GENERAL_MART_SCHEMA
              value: jw_mart_d2_stage_20260630_r2
            - name: CHAT_CD_MART_SCHEMA
              value: jw_mart_d2_stage_20260630_r2
