from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Sequence


@dataclass(frozen=True)
class BrandMetadata:
    brand: str
    market_id: str
    market_name: str
    market_name_short: str
    market_label_kor: str
    mkt_team: str | None
    sources: list[str]
    atc_desc: str
    is_jw: bool
    is_target: bool
    is_dual_source: bool
    rank: int

    def to_response(self, *, atc_codes: list[str]) -> dict[str, object]:
        return {
            "brand": self.brand,
            "market_id": self.market_id,
            "market_name": self.market_name,
            "market_name_short": self.market_name_short,
            "market_label_kor": self.market_label_kor,
            "mkt_team": self.mkt_team,
            "sources": list(self.sources),
            "atc_codes": list(atc_codes),
            "atc_desc": self.atc_desc,
            "is_jw": self.is_jw,
            "is_target": self.is_target,
            "is_dual_source": self.is_dual_source,
            "rank": self.rank,
        }


def build_brand_metadata_payload(
    atc_codes_by_market: Mapping[str, Sequence[str]],
) -> list[dict[str, object]]:
    missing = sorted(
        {meta.market_id for meta in BRAND_METADATA} - atc_codes_by_market.keys()
    )
    if missing:
        raise ValueError(f"brand metadata markets missing from ml market catalog: {missing}")
    empty = sorted(
        {
            meta.market_id
            for meta in BRAND_METADATA
            if not atc_codes_by_market[meta.market_id]
        }
    )
    if empty:
        raise ValueError(f"brand metadata markets have empty ATC codes: {empty}")
    return [
        meta.to_response(atc_codes=list(atc_codes_by_market[meta.market_id]))
        for meta in BRAND_METADATA
    ]


BRAND_METADATA: tuple[BrandMetadata, ...] = (
    BrandMetadata(
        brand="라베칸",
        market_id="strategy_001",
        market_name="라베칸/라베칸듀오",
        market_name_short="라베칸",
        market_label_kor="위궤양/PPI",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="PROTON PUMP INHIBITORS (PPI)",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="라베칸듀오",
        market_id="strategy_001",
        market_name="라베칸/라베칸듀오",
        market_name_short="라베칸",
        market_label_kor="위궤양/PPI",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="PROTON PUMP INHIBITORS (PPI)",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=3,
    ),
    BrandMetadata(
        brand="제이클",
        market_id="strategy_002",
        market_name="제이클",
        market_name_short="제이클",
        market_label_kor="장정결",
        mkt_team="MKT 1팀",
        sources=["IQVIA"],
        atc_desc="OSMOTIC BOWEL CLEANSERS",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="가드렛",
        market_id="strategy_003",
        market_name="가드렛/가드메트",
        market_name_short="가드렛",
        market_label_kor="당뇨",
        mkt_team="MKT 1팀",
        sources=["UBIST", "IQVIA"],
        atc_desc="DPP-IV INH A-DIAB PLAIN (OAD 시장)",
        is_jw=True,
        is_target=True,
        is_dual_source=True,
        rank=1,
    ),
    BrandMetadata(
        brand="가드메트",
        market_id="strategy_003",
        market_name="가드렛/가드메트",
        market_name_short="가드렛",
        market_label_kor="당뇨",
        mkt_team="MKT 1팀",
        sources=["UBIST", "IQVIA"],
        atc_desc="DPP-IV INH A-DIAB PLAIN (OAD 시장)",
        is_jw=True,
        is_target=False,
        is_dual_source=True,
        rank=3,
    ),
    BrandMetadata(
        brand="타발리스",
        market_id="strategy_004",
        market_name="타발리스",
        market_name_short="타발리스",
        market_label_kor="혈소판",
        mkt_team="MKT 1팀",
        sources=["IQVIA"],
        atc_desc="PLATELET-ENHAN PRDS OTH",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="시그마트",
        market_id="strategy_005",
        market_name="시그마트",
        market_name_short="시그마트",
        market_label_kor="협심증",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="CORONARY THERAPY",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="리바로",
        market_id="strategy_006",
        market_name="리바로/리바로젯",
        market_name_short="리바로",
        market_label_kor="고지혈증",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="STATINS (HMG-COA RED) + 복합제제",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="리바로젯",
        market_id="strategy_006",
        market_name="리바로/리바로젯",
        market_name_short="리바로",
        market_label_kor="고지혈증",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="STATINS (HMG-COA RED) + 복합제제",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=2,
    ),
    BrandMetadata(
        brand="리바로페노",
        market_id="strategy_007",
        market_name="리바로페노",
        market_name_short="리바로페노",
        market_label_kor="고지혈증/복합",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="LIP.REG.CO.W.OTH.LIP.REG (지질조절제 복합)",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="리바로하이",
        market_id="strategy_008",
        market_name="리바로하이/리바로브이",
        market_name_short="리바로하이",
        market_label_kor="고혈압/복합",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="심혈관 다중요법 복합제 + 고혈압",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="리바로브이",
        market_id="strategy_008",
        market_name="리바로하이/리바로브이",
        market_name_short="리바로하이",
        market_label_kor="고혈압/복합",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="심혈관 다중요법 복합제 + 고혈압",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=2,
    ),
    BrandMetadata(
        brand="트루패스",
        market_id="strategy_009",
        market_name="트루패스/피나스타/제이다트",
        market_name_short="트루패스",
        market_label_kor="전립선비대증",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="BPH (전립선비대증)",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="피나스타",
        market_id="strategy_009",
        market_name="트루패스/피나스타/제이다트",
        market_name_short="트루패스",
        market_label_kor="전립선비대증",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="BPH (전립선비대증)",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=2,
    ),
    BrandMetadata(
        brand="제이다트",
        market_id="strategy_009",
        market_name="트루패스/피나스타/제이다트",
        market_name_short="트루패스",
        market_label_kor="전립선비대증",
        mkt_team="MKT 1팀",
        sources=["UBIST"],
        atc_desc="BPH (전립선비대증)",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=3,
    ),
    BrandMetadata(
        brand="뉴트로진",
        market_id="strategy_010",
        market_name="뉴트로진/모빌리아",
        market_name_short="뉴트로진",
        market_label_kor="G-CSF",
        mkt_team="MKT 1팀",
        sources=["IQVIA"],
        atc_desc="COLONY-STIMULATING FACT (G-CSF)",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="모빌리아",
        market_id="strategy_010",
        market_name="뉴트로진/모빌리아",
        market_name_short="뉴트로진",
        market_label_kor="조혈모세포 가동화 촉진",
        mkt_team="MKT 1팀",
        sources=["IQVIA"],
        atc_desc="COLONY-STIMULATING FACT (G-CSF)",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=3,
    ),
    BrandMetadata(
        brand="악템라",
        market_id="strategy_011",
        market_name="악템라",
        market_name_short="악템라",
        market_label_kor="항류마티스",
        mkt_team="MKT 1팀",
        sources=["IQVIA"],
        atc_desc="SPEC ANTIRHEUMATIC AGENT",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="페린젝트",
        market_id="strategy_012",
        market_name="페린젝트/베노훼럼",
        market_name_short="페린젝트",
        market_label_kor="철결핍",
        mkt_team="MKT 2팀",
        sources=["IQVIA"],
        atc_desc="IRON PLAIN + COMBINATION",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="베노훼럼",
        market_id="strategy_012",
        market_name="페린젝트/베노훼럼",
        market_name_short="페린젝트",
        market_label_kor="철결핍",
        mkt_team="MKT 2팀",
        sources=["IQVIA"],
        atc_desc="IRON PLAIN + COMBINATION",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=2,
    ),
    BrandMetadata(
        brand="헴리브라",
        market_id="strategy_013",
        market_name="헴리브라",
        market_name_short="헴리브라",
        market_label_kor="혈우병",
        mkt_team="MKT 2팀",
        sources=["IQVIA"],
        atc_desc="FACTOR VIII INCL SUBSTIT",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="위너프",
        market_id="strategy_014",
        market_name="위너프/A+",
        market_name_short="위너프",
        market_label_kor="TPN",
        mkt_team="MKT 3팀",
        sources=["IQVIA"],
        atc_desc="FAT EMULSIONS,COMBINAT (TPN)",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
    BrandMetadata(
        brand="위너프A+",
        market_id="strategy_014",
        market_name="위너프/A+",
        market_name_short="위너프",
        market_label_kor="TPN",
        mkt_team="MKT 3팀",
        sources=["IQVIA"],
        atc_desc="FAT EMULSIONS,COMBINAT (TPN)",
        is_jw=True,
        is_target=False,
        is_dual_source=False,
        rank=2,
    ),
    BrandMetadata(
        brand="엔커버",
        market_id="strategy_015",
        market_name="엔커버",
        market_name_short="엔커버",
        market_label_kor="영양제",
        mkt_team="MKT 2팀",
        sources=["IQVIA", "UBIST"],
        atc_desc="OTHER GENERAL NUTRIENTS",
        is_jw=True,
        is_target=True,
        is_dual_source=True,
        rank=1,
    ),
    BrandMetadata(
        brand="플라주오피",
        market_id="strategy_016",
        market_name="플라주오피",
        market_name_short="플라주오피",
        market_label_kor="전해질",
        mkt_team="MKT 3팀",
        sources=["IQVIA"],
        atc_desc="1/2-ELECTROLYTE SOLUTIONS",
        is_jw=True,
        is_target=True,
        is_dual_source=False,
        rank=1,
    ),
)
