apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmops-market-output
  namespace: llmops
  labels:
    app: jw-ingest-hook
    jw.track/purpose: market-output
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
