-- DEPRECATED: split into explicit target migrations.
--
-- Do not apply this file. It intentionally contains no DDL because the previous
-- combined migration tried to alter zeta_analysis_runs before adding operational
-- cache columns. Production jw_mart may not contain zeta_analysis_runs, causing
-- the combined migration to fail before cache_deep_analysis_ai_analysis receives
-- ai_analysis_short_json/ai_analysis_long_json.
--
-- Use instead:
--   021a_cache_ai_variant_columns.sql
--     Operational cache DB only; additive sibling JSON columns.
--   021b_zeta_runs_variant.sql
--     Agent2 generation DB only; requires zeta_analysis_runs to exist and a
--     duplicate preflight on (brand, snapshot_at).
