from __future__ import annotations

from typing import Any

CD_SPECS: tuple[dict[str, Any], ...] = (
    {
        "competitive_dynamics_id": "cd_001",
        "strategic_market_id": "strategy_001",
        "product_name_kor": "라베칸/라베칸듀오",
        "col_in_master_excel": "C",
        "column_ids": (3,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "Rabeprazole 단일제 + Rabeprazole/제산제 FDC",
        "cd_filter_expression": "clean(molecule) == 'Rabeprazole'",
        "filter_kind": "molecule_rabeprazole",
    },
    {
        "competitive_dynamics_id": "cd_002",
        "strategic_market_id": "strategy_002",
        "product_name_kor": "제이클",
        "col_in_master_excel": "D",
        "column_ids": (4,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "NON_NHI",
        "cd_filter_expression": "clean(nhi_type) == 'NON-NHI'",
        "filter_kind": "nhi_non_nhi",
    },
    {
        "competitive_dynamics_id": "cd_003",
        "strategic_market_id": "strategy_003",
        "product_name_kor": "가드렛/가드메트",
        "col_in_master_excel": "E",
        "column_ids": (5,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "A10N3 + A10N1",
        "cd_filter_expression": "atc4_code contains A10N3 or A10N1",
        "filter_kind": "atc_a10n3_a10n1",
    },
    {
        "competitive_dynamics_id": "cd_004",
        "strategic_market_id": "strategy_004",
        "product_name_kor": "타발리스",
        "col_in_master_excel": "F",
        "column_ids": (6,),
        "cd_definition_type": "ml_equals_cd_exact",
        "cd_definition_brand_class": "default",
        "cd_filter_expression": "sheet 전체",
        "filter_kind": "sheet_all",
    },
    {
        "competitive_dynamics_id": "cd_005",
        "strategic_market_id": "strategy_005",
        "product_name_kor": "시그마트",
        "col_in_master_excel": "G",
        "column_ids": (7,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "C01D0 -> [C1D] only",
        "cd_filter_expression": "Q-29 option B: atc4_code contains [C1D] only",
        "filter_kind": "sigmart_c1d_only",
        "cd_filter_status": "confirmed_q29_b",
    },
    {
        "competitive_dynamics_id": "cd_006",
        "strategic_market_id": "strategy_006",
        "product_name_kor": "리바로/리바로젯",
        "col_in_master_excel": "H",
        "column_ids": (8,),
        "cd_definition_type": "ml_equals_cd_exact",
        "cd_definition_brand_class": "default",
        "cd_filter_expression": "sheet 전체",
        "filter_kind": "sheet_all",
    },
    {
        "competitive_dynamics_id": "cd_007",
        "strategic_market_id": "strategy_007",
        "product_name_kor": "리바로페노",
        "col_in_master_excel": "I",
        "column_ids": (9,),
        "cd_definition_type": "ml_equals_cd_exact",
        "cd_definition_brand_class": "default",
        "cd_filter_expression": "sheet 전체",
        "filter_kind": "sheet_all",
    },
    {
        "competitive_dynamics_id": "cd_008",
        "strategic_market_id": "strategy_008",
        "product_name_kor": "리바로하이",
        "col_in_master_excel": "J",
        "column_ids": (10,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "Statin/ARB/CCB",
        "cd_filter_expression": "corrected explicit lookup clean(class_2) == 'Statin/ARB/CCB'",
        "filter_kind": "class2_statin_arb_ccb",
    },
    {
        "competitive_dynamics_id": "cd_009",
        "strategic_market_id": "strategy_008",
        "product_name_kor": "리바로브이",
        "col_in_master_excel": "K",
        "column_ids": (11,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "Statin/ARB",
        "cd_filter_expression": "corrected explicit lookup clean(class_2) == 'Statin/ARB'",
        "filter_kind": "class2_statin_arb",
    },
    {
        "competitive_dynamics_id": "cd_010",
        "strategic_market_id": "strategy_009",
        "product_name_kor": "트루패스",
        "col_in_master_excel": "L",
        "column_ids": (12,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "G4C2",
        "cd_filter_expression": "atc4_code contains G4C2",
        "filter_kind": "atc_g4c2",
    },
    {
        "competitive_dynamics_id": "cd_011",
        "strategic_market_id": "strategy_009",
        "product_name_kor": "피나스타/제이다트",
        "col_in_master_excel": "M",
        "column_ids": (13,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "G4C3",
        "cd_filter_expression": "atc4_code contains G4C3",
        "filter_kind": "atc_g4c3",
    },
    {
        "competitive_dynamics_id": "cd_012",
        "strategic_market_id": "strategy_010",
        "product_name_kor": "뉴트로진",
        "col_in_master_excel": "N",
        "column_ids": (14,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "L03A1",
        "cd_filter_expression": "clean(atc4_code) == 'L03A1'",
        "filter_kind": "atc_l03a1",
    },
    {
        "competitive_dynamics_id": "cd_013",
        "strategic_market_id": "strategy_010",
        "product_name_kor": "모빌리아",
        "col_in_master_excel": "O",
        "column_ids": (15,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "L03A9",
        "cd_filter_expression": "clean(atc4_code) == 'L03A9'",
        "filter_kind": "atc_l03a9",
    },
    {
        "competitive_dynamics_id": "cd_014",
        "strategic_market_id": "strategy_011",
        "product_name_kor": "악템라",
        "col_in_master_excel": "P",
        "column_ids": (16,),
        "cd_definition_type": "ml_equals_cd_by_empty",
        "cd_definition_brand_class": "default_sheet_all",
        "cd_filter_expression": "R48-R50 empty -> sheet 전체",
        "filter_kind": "sheet_all",
    },
    {
        "competitive_dynamics_id": "cd_015",
        "strategic_market_id": "strategy_012",
        "product_name_kor": "페린젝트 + 베노훼럼",
        "col_in_master_excel": "Q+R",
        "column_ids": (17, 18),
        "cd_definition_type": "collapse_pair",
        "cd_definition_brand_class": "IV Iron",
        "cd_filter_expression": "clean(atc4_code) == 'B03A1' and clean(dosage_form) == 'IV Iron'",
        "filter_kind": "b03a1_iv_iron",
    },
    {
        "competitive_dynamics_id": "cd_016",
        "strategic_market_id": "strategy_013",
        "product_name_kor": "헴리브라",
        "col_in_master_excel": "S",
        "column_ids": (19,),
        "cd_definition_type": "ml_equals_cd_exact",
        "cd_definition_brand_class": "default",
        "cd_filter_expression": "sheet 전체",
        "filter_kind": "sheet_all",
    },
    {
        "competitive_dynamics_id": "cd_017",
        "strategic_market_id": "strategy_015",
        "product_name_kor": "엔커버",
        "col_in_master_excel": "T",
        "column_ids": (20,),
        "cd_definition_type": "ml_equals_cd_exact",
        "cd_definition_brand_class": "default",
        "cd_filter_expression": "sheet 전체",
        "filter_kind": "sheet_all",
    },
    {
        "competitive_dynamics_id": "cd_018",
        "strategic_market_id": "strategy_014",
        "product_name_kor": "위너프/위너프A+",
        "col_in_master_excel": "U",
        "column_ids": (21,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "3CB & NHI & strength exists",
        "cd_filter_expression": "clean(class) == '3CB' and clean(nhi_type) == 'NHI' and clean(strength) is not null",
        "filter_kind": "winnerf_3cb_nhi_strength",
    },
    {
        "competitive_dynamics_id": "cd_019",
        "strategic_market_id": "strategy_016",
        "product_name_kor": "플라주오피",
        "col_in_master_excel": "V",
        "column_ids": (22,),
        "cd_definition_type": "filter_explicit",
        "cd_definition_brand_class": "Acetated Balanced Crystalloid",
        "cd_filter_expression": "clean(atc4_code) in (K01A1,K01A3) and clean(class) == 'Acetated Balanced Crystalloid'",
        "filter_kind": "plajuopi_acetated",
    },
)
